# Generated by Django 2.1 on 2018-08-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plans',
                'managed': False,
            },
        ),
    ]
